theme: jekyll-theme-cayman
name: Michael Burns
description: DevOps Engineer in Portland, OR
avatar: https://raw.githubusercontent.com/mburns/mburns.github.io/master/images/avatar.jpg
disqus: mburns
google_analytics: UA-100890000-1
footer-links:
  email:
  flickr:
  googleplus: 107225813711437200584
  linkedin: maburns
  twitter: mburns
github:
  repo: mburns/mburns.github.io
  branch: master
gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-seo-tag
   - jekyll-sitemap
   - jekyll-feed
