theme: jekyll-theme-cayman
name: Michael Burns
description: DevOps Engineer in Portland, OR
google_analytics: UA-100890000-1
footer-links:
  linkedin: maburns
  twitter: mburns
github:
  repo: mburns/mburns.github.io
  branch: master